### ISSUE TITLE
Object of class DateTime could not be converted to string

### ISSUE THREAD

**Issue by amjadsoftrove** [tebazil/db-seeder#1]
I m getting the following error when i run db seed

'Object of class DateTime could not be converted to string'

following is my seed

$seeder->table('book')->columns([
            'id',
            'name'=>$faker->text(20),
            'updated'=>$faker->dateTime,
        ])->rowQuantity(3000);

**Comment by vambus** [comment]
Well, this is a faker behavior and is expected. Faker's dateTime provider returns a php DateTime object, which cannot be converted to a string directly. And something like $faker->dateTime->format('r') won't work in FakerWrapper, which is a `$faker` in your example for technical reasons atm.

Things you could do ATM:
- Use datetime provider that returns string. See https://github.com/fzaninotto/Faker#fakerproviderdatetime , it has date and time providers.
- Make your own anonymous function provider, i.e.

``` php
function() {
  return date('Y-m-d H:i:s', rand(0, time());
}
```

Anyway, you have raised a reasonable issue.

We should either allow a user to use $faker in anonymous function provider, or make DateTime format support in FakerWrapper, or both.

I'll try to fix it when I have time.

Feel free to ask more questions if you have them.

Thanks!

**Comment by webvimark** [comment]
Hi @tebazil 
First - your seeder is awesome!
Second - handling automatically DateTime by FakerWrapper would be great :)

**Comment by vambus** [comment]
@webvimark , thanks!
> handling automatically DateTime by FakerWrapper would be great
Noted. I plan to add it during this month.

**Comment by vambus** [comment]
@amjadsoftrove , @webvimark if that is possible to remember (years have passed), could you please tell why couldn't we use 'updated'=>$faker->dateTime() ? 
That is s method call, and that should have worked.

**Comment by automatix** [comment]
Hello everyone,

Yes, the issue is still there:

```
Fatal error: Uncaught Error: Object of class DateTime could not be converted to string in /path/to/data-generator/vendor/tebazil/db-seeder/src/DbHelper.php:54
Stack trace:
#0 /path/to/data-generator/vendor/tebazil/db-seeder/src/DbHelper.php(35): tebazil\dbseeder\DbHelper->getParamsForEcho(Array)
#1 /path/to/data-generator/vendor/tebazil/db-seeder/src/Table.php(196): tebazil\dbseeder\DbHelper->insert('ordering_test', Array)
#2 /path/to/data-generator/vendor/tebazil/db-seeder/src/Table.php(98): tebazil\dbseeder\Table->insertData()
#3 /path/to/data-generator/vendor/tebazil/db-seeder/src/Seeder.php(50): tebazil\dbseeder\Table->fill()
#4 /path/to/data-generator/seeder.php(81): tebazil\dbseeder\Seeder->refill()
#5 {main}
  thrown in /path/to/data-generator/vendor/tebazil/db-seeder/src/DbHelper.php on line 54
```

So, it's the [`Dbhelper#getParamsForEcho(...)`](https://github.com/tebazil/db-seeder/blob/master/src/DbHelper.php#L54). The same error occurs in the [Dbhelper#insert(...)](https://github.com/tebazil/db-seeder/blob/master/src/DbHelper.php#L30).

I solved that for me now with `$value = $value instanceof \DateTime ? $value->format('Y-m-d H:i:s') : $value;` at both places. But it's just a hacky workaround and not a clean solution.

**Comment by vambus** [comment]
@automatix it is clear that DbHelper, which is responsible for db operation, should work with scalar values... 
For the moment, I think we might fix this with some configurator hack... 
Thanks for the feedback!
