### ISSUE TITLE
Table data for table (table) column id is not found in class instance

### ISSUE THREAD

**Issue by goestav** [tebazil/db-seeder#8]
Hi, I have a problem.
When I run the seeder script it stops and shows an error when it tries to use the relation function.

Terminal:
```
Fatal error: Uncaught InvalidArgumentException: Table data for table quality_list column id is not found in class instance. Probably this is a bug. in /project/vendor/tebazil/db-seeder/src/Generator.php:57
Stack trace:
#0 /project/vendor/tebazil/db-seeder/src/Table.php(149): tebazil\dbseeder\Generator->getValue(Array)
#1 /project/vendor/tebazil/db-seeder/src/Table.php(82): tebazil\dbseeder\Table->fillFromGenerators(Array)
#2 /project/vendor/tebazil/db-seeder/src/Seeder.php(50): tebazil\dbseeder\Table->fill()
#3 /project/seeder.php(67): tebazil\dbseeder\Seeder->refill()
#4 {main}
  thrown in /project/vendor/tebazil/db-seeder/src/Generator.php on line 57
```

PHP code:
```
...
// Media
$seeder->table('media')->columns([
    'duration' => $faker->numberBetween(60, 180),
    'imdb_id' => 'tt'.$faker->numberBetween(1000000, 9999999),
    'release_date' => $faker->dateTimeThisDecade(),
    'rating' => $faker->randomFloat(1, 0, 10),
    'summary' => $faker->text(),
    'dirname' => $faker->text(),
    'tmdb_poster_url' => $faker->url(),
    'quality_id' => $generator->relation('quality_list', 'id'), // <- stops here
    'added_by_user_id' => $generator->relation('users', 'id'),
    'type_id' => $generator->relation('media_types', 'id'),
    'status_id' => $generator->relation('media_status', 'id')
])->rowQuantity(150);


// Empty database and fill
$seeder->refill();
```

**Comment by vambus** [comment]
@goestav was table `quality_list` properly configured? 
You will need to use anonymous function generator (manual) with quality_list table data if that is an existing table with data.
`db-seeder` relation allows you to configure the table for being re-filled with some faker data, not using existing table data.
